# Generated by Django 5.0.7 on 2026-08-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_reference', models.CharField(help_text='Human-readable pointer to what this resource represents, e.g. "MeasureReport: ANC 1st visit / Bo / 202508".', max_length=255)),
                ('fhir_json', models.JSONField()),
                ('fhir_release', models.CharField(default='R4', max_length=10)),
                ('validator_used', models.CharField(default='HAPI FHIR JPA server ($validate)', max_length=255)),
                ('is_valid', models.BooleanField()),
                ('issues', models.JSONField(blank=True, default=list, help_text='OperationOutcome.issue entries returned by the validator.')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-validated_at'],
            },
        ),
    ]
