# Generated by Django 5.0.7 on 2026-08-10 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dhis2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_org_unit_uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dhis2_dx_uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, default='')),
                ('data_owner', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('refresh_date', models.DateTimeField(blank=True, null=True)),
                ('geographic_coverage', models.CharField(blank=True, default='', max_length=255)),
                ('temporal_coverage_start', models.CharField(blank=True, default='', max_length=20)),
                ('temporal_coverage_end', models.CharField(blank=True, default='', max_length=20)),
                ('schema_version', models.CharField(default='1.0', max_length=20)),
                ('sensitivity_classification', models.CharField(choices=[('public', 'Public'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='restricted', max_length=20)),
                ('transformation_status', models.CharField(choices=[('raw_only', 'Raw only'), ('canonical', 'Canonical'), ('fhir_mapped', 'FHIR mapped')], default='raw_only', max_length=20)),
                ('quality_status', models.CharField(choices=[('unscreened', 'Unscreened'), ('passed', 'Passed'), ('flagged', 'Flagged')], default='unscreened', max_length=20)),
                ('permitted_audience', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_products', to='data_products.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('value', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='data_products.district')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='data_products.indicator')),
                ('source_raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='dhis2.rawdhis2record')),
            ],
            options={
                'ordering': ['district__name', 'indicator__name', 'period'],
            },
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('indicator', 'district', 'period'), name='unique_observation_indicator_district_period'),
        ),
    ]
