# Generated by Django 5.0.7 on 2026-08-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='join_strategy',
            field=models.TextField(blank=True, default='', help_text='How multiple sources were reconciled/joined (join key, unmatched handling).'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='transformation_description',
            field=models.TextField(blank=True, default='', help_text='The transformation/formula applied, e.g. a derived metric definition.'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_products', to='data_products.indicator'),
        ),
        migrations.CreateModel(
            name='DataProductSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Sierra Leone DHIS2" or the dataset\'s formal name.', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('extraction_date', models.DateField(blank=True, help_text='When this source was pulled/extracted, if applicable.', null=True)),
                ('reference_period', models.CharField(blank=True, default='', help_text='The period the source data itself refers to, e.g. "2021" for a census year.', max_length=50)),
                ('data_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='data_products.dataproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
