# Generated by Django 5.0.7 on 2026-08-11 14:00

import django.db.models.deletion
from django.db import migrations, models


def remap_old_quality_status_values(apps, schema_editor):
    """FR6.6 renamed quality_status's choices from unscreened/passed/
    flagged to unscreened/publishable/publishable_with_warnings/blocked.
    No real patient data is at stake (dev/demo data only, recreated by
    the management commands) - this just carries forward any
    already-synced rows' intent instead of silently stranding them on a
    value that's no longer a valid choice.
    """
    DataProduct = apps.get_model('data_products', 'DataProduct')
    DataProduct.objects.filter(quality_status='passed').update(quality_status='publishable')
    DataProduct.objects.filter(quality_status='flagged').update(quality_status='publishable_with_warnings')


class Migration(migrations.Migration):

    dependencies = [
        ('data_products', '0002_dataproduct_join_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='governance_reviewed',
            field=models.BooleanField(default=False, help_text='A data steward has reviewed sensitivity_classification and permitted_audience for this product. Required before it can be marked publishable.'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='quality_status',
            field=models.CharField(choices=[('unscreened', 'Unscreened'), ('publishable', 'Publishable'), ('publishable_with_warnings', 'Publishable with warnings'), ('blocked', 'Blocked')], default='unscreened', max_length=30),
        ),
        migrations.CreateModel(
            name='QualityCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_code', models.CharField(max_length=50)),
                ('check_name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('deterministic', 'Deterministic'), ('heuristic', 'Heuristic'), ('human_required', 'Requires human approval')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('blocker', 'Blocker')], max_length=10)),
                ('passed', models.BooleanField()),
                ('detail', models.TextField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('data_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='data_products.dataproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(remap_old_quality_status_values, migrations.RunPython.noop),
    ]
