# Generated by Django 5.0.7 on 2026-08-11 15:17

from django.db import migrations, models

# FR6.7: SensitivityClassification grows from 3 tiers to the spec's
# required 6-tier taxonomy. The old tiers map onto the nearest new tier
# rather than being dropped - 'restricted' (the old default, meaning
# "not for general release") becomes 'internal'; 'confidential' becomes
# 'sensitive'. Neither old tier implied personal/identifying data, so
# nothing maps onto the new, more-restrictive 'personal'/
# 'potentially_identifying'/'prohibited' tiers - a human must
# deliberately move a product into one of those through the admin.
_OLD_TO_NEW = {'restricted': 'internal', 'confidential': 'sensitive'}


def _forwards(apps, schema_editor):
    DataProduct = apps.get_model('data_products', 'DataProduct')
    for old, new in _OLD_TO_NEW.items():
        DataProduct.objects.filter(sensitivity_classification=old).update(sensitivity_classification=new)


def _backwards(apps, schema_editor):
    DataProduct = apps.get_model('data_products', 'DataProduct')
    for old, new in _OLD_TO_NEW.items():
        DataProduct.objects.filter(sensitivity_classification=new).update(sensitivity_classification=old)


class Migration(migrations.Migration):

    dependencies = [
        ('data_products', '0003_dataproduct_governance_reviewed_and_more'),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
        migrations.AlterField(
            model_name='dataproduct',
            name='sensitivity_classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('sensitive', 'Sensitive'), ('personal', 'Personal'), ('potentially_identifying', 'Potentially identifying'), ('prohibited', 'Prohibited from publication')], default='prohibited', max_length=30),
        ),
    ]
