# Generated by Django 5.0.7 on 2026-08-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_products', '0004_alter_dataproduct_sensitivity_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(help_text='Username for a request-triggered action, or a "system:<command>" label for an unattended pipeline run - never blank.', max_length=150)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('authentication', 'Authentication attempt'), ('access_denied', 'Access denied'), ('data_acquisition', 'Data acquisition'), ('data_transformation', 'Data transformation'), ('data_validation', 'Data validation'), ('dataset_publication', 'Dataset publication'), ('dataset_view', 'Dataset viewing'), ('dataset_download', 'Dataset downloading'), ('admin_change', 'Administrative change')], max_length=30)),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('denied', 'Denied'), ('failure', 'Failure')], max_length=10)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='audit_audit_action_d7f04a_idx'), models.Index(fields=['actor', 'timestamp'], name='audit_audit_actor_a1e515_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('activity', models.CharField(choices=[('acquired', 'Acquired from source'), ('transformed', 'Transformed to canonical model'), ('validated', 'Validated'), ('derived', 'Derived/joined from other datasets')], max_length=20)),
                ('description', models.TextField()),
                ('source_reference', models.CharField(blank=True, default='', help_text='What this activity read from, e.g. a DHIS2 dx/org-unit/period slice.', max_length=255)),
                ('performed_by', models.CharField(max_length=150)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=36)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenance_records', to='data_products.dataproduct')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
