# Generated by Django 5.0.7 on 2026-08-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_products', '0002_dataproduct_join_strategy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('missing_population', 'Missing population value'), ('missing_dhis2_observation', 'Missing DHIS2 observation'), ('unknown_district', 'Unknown/unmatched district'), ('duplicate_record', 'Duplicate district record'), ('conflicting_identifier', 'Conflicting district identifier or figures'), ('out_of_period', 'Population data outside the reporting period'), ('stale_data', 'Stale/outdated population data')], max_length=30)),
                ('district_name', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='RawPopulationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('district_name', models.CharField(help_text='District name exactly as it appears in the source.', max_length=100)),
                ('male', models.PositiveIntegerField()),
                ('female', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('sex_ratio', models.FloatField()),
                ('reference_year', models.PositiveSmallIntegerField(default=2021)),
                ('source_document', models.CharField(default='Statistics Sierra Leone - 2021 Mid-Term Population and Housing Census, Final Results by District (2022-09-22)', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['region', 'district_name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.PositiveIntegerField()),
                ('reference_year', models.PositiveSmallIntegerField()),
                ('source_record_count', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='data_products.district')),
            ],
            options={
                'ordering': ['district__name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictPopulationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_district_name', models.CharField(max_length=100, unique=True)),
                ('dhis2_district_hint', models.CharField(blank=True, default='', help_text='District name to (re-)resolve dhis2_district against if it is still null - e.g. on a fresh DB migrated before fetch_dhis2_data has ever run. Defaults to population_district_name when blank; only needs to differ for an aggregate match (e.g. "Western Area" for the West Rural/West Urban rows). Unused for match_type=unmatched.', max_length=100)),
                ('match_type', models.CharField(choices=[('exact', 'Exact name match'), ('aggregate', 'Aggregated into a DHIS2 district'), ('unmatched', 'No DHIS2 counterpart')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('dhis2_district', models.ForeignKey(blank=True, help_text='Null means either deliberately unmatched (see notes), or not yet resolved because this District did not exist when the mapping was seeded - see dhis2_district_hint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='population_mappings', to='data_products.district')),
            ],
            options={
                'ordering': ['population_district_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rawpopulationrecord',
            constraint=models.UniqueConstraint(fields=('district_name', 'reference_year'), name='unique_population_record_district_year'),
        ),
        migrations.AddConstraint(
            model_name='districtpopulation',
            constraint=models.UniqueConstraint(fields=('district', 'reference_year'), name='unique_district_population_year'),
        ),
    ]
