# Generated by Django 5.0.7 on 2026-08-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawDHIS2Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx_uid', models.CharField(max_length=50)),
                ('dx_name', models.CharField(max_length=255)),
                ('org_unit_uid', models.CharField(max_length=50)),
                ('org_unit_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('raw_payload', models.JSONField()),
                ('source_url', models.URLField(max_length=500)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['org_unit_name', 'dx_name', 'period'],
            },
        ),
        migrations.AddConstraint(
            model_name='rawdhis2record',
            constraint=models.UniqueConstraint(fields=('dx_uid', 'org_unit_uid', 'period'), name='unique_dhis2_record_dx_ou_period'),
        ),
    ]
