# Generated by Django 5.0.7 on 2026-08-11 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(default='DHIS2', help_text='e.g. "DHIS2" or "LOCAL" for a concept with no DHIS2 origin.', max_length=100)),
                ('source_code', models.CharField(help_text="The source system's own identifier, e.g. Indicator.dhis2_dx_uid.", max_length=100)),
                ('source_display', models.CharField(help_text='Source concept/name, e.g. "Malaria cases".', max_length=255)),
                ('target_terminology', models.CharField(blank=True, choices=[('icd10', 'ICD-10'), ('icd11', 'ICD-11'), ('loinc', 'LOINC'), ('snomed_ct', 'SNOMED CT'), ('other', 'Other')], default='', max_length=20)),
                ('target_code', models.CharField(blank=True, default='', max_length=50)),
                ('target_display', models.CharField(blank=True, default='', max_length=255)),
                ('terminology_version', models.CharField(blank=True, default='', help_text='The exact terminology release used, e.g. "ICD-10 2019" - required for reproducibility.', max_length=50)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('unmapped', 'Unmapped')], default='proposed', max_length=20)),
                ('mapping_method', models.CharField(choices=[('manual', 'Manual (entered by a data steward)'), ('semantic_search', 'Semantic search (heuristic text match, AI-assisted)')], default='manual', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='Similarity score from an automated/semantic proposal. Never set for manual mappings.', null=True)),
                ('rationale', models.TextField(help_text='Why this target code was proposed/accepted/rejected.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, help_text='Set only by human review (apps.terminology.services.review_mapping) - never by automation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminology_mapping_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_system', 'source_code', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='terminologymapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('source_system', 'source_code', 'target_terminology'), name='unique_accepted_mapping_per_source_and_terminology'),
        ),
    ]
