from django.contrib import admin

from .models import DistrictPopulation, DistrictPopulationMapping, PopulationDataQualityIssue, RawPopulationRecord


@admin.register(RawPopulationRecord)
class RawPopulationRecordAdmin(admin.ModelAdmin):
    """Unmodified source data - never edited directly, same pattern as
    RawDHIS2RecordAdmin."""
    list_display = ('district_name', 'region', 'total', 'reference_year', 'imported_at')
    list_filter = ('region', 'reference_year')
    search_fields = ('district_name',)
    readonly_fields = (
        'region', 'district_name', 'male', 'female', 'total', 'sex_ratio',
        'reference_year', 'source_document', 'imported_at',
    )


@admin.register(DistrictPopulationMapping)
class DistrictPopulationMappingAdmin(admin.ModelAdmin):
    """The explicit, human-maintained geographic identifier mapping -
    editable here, the same "governance judgement, human-maintained"
    pattern as DataProduct's judgement fields."""
    list_display = ('population_district_name', 'dhis2_district', 'match_type')
    list_filter = ('match_type',)
    search_fields = ('population_district_name',)


@admin.register(DistrictPopulation)
class DistrictPopulationAdmin(admin.ModelAdmin):
    """Derived by reconcile_population() - read-only, re-running the
    reconciliation is the only way to change these."""
    list_display = ('district', 'reference_year', 'total_population', 'source_record_count', 'updated_at')
    list_filter = ('reference_year',)
    readonly_fields = ('district', 'total_population', 'reference_year', 'source_record_count', 'updated_at')


@admin.register(PopulationDataQualityIssue)
class PopulationDataQualityIssueAdmin(admin.ModelAdmin):
    """The data-quality report - read-only, regenerated by every
    reconcile_population() run."""
    list_display = ('issue_type', 'district_name', 'detected_at')
    list_filter = ('issue_type',)
    search_fields = ('district_name', 'detail')
    readonly_fields = ('issue_type', 'district_name', 'detail', 'detected_at')
